import type { Metadata } from 'next'
import './globals.css'

export const metadata = {
  title: 'FrikiWiki',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="text-gray-600 px-4">{children}</body>
    </html>
  )
}
